/* eslint-disable */
/* oxlint-disable */
// Auto-generated by @contentrain/query — do not edit manually
// Re-generate with: npx contentrain-query generate

export type ContentStatus = 'draft' | 'published' | 'in_review' | 'rejected' | 'archived'

export interface DocsPage {
  slug: string
  content: string
  description?: string
  features?: { details: string; icon?: string; title: string }[]
  hero?: { actions?: { link: string; text: string; theme?: 'brand' | 'alt' }[]; image?: string; name?: string; tagline?: string; text?: string }
  layout?: 'doc' | 'home'
  order?: number
  sidebar_label?: string
  slug: string
  title: string
}

export interface Footer {
  blurb?: string
  columns?: { links?: { href: string; label: string }[]; title: string }[]
  legal_notice?: string
}

export interface GuidePage {
  slug: string
  content: string
  description?: string
  order?: number
  sidebar_label?: string
  slug: string
  title: string
}

export interface Navigation {
  announcement_label?: string
  cta_href?: string
  cta_label?: string
  items?: { emphasis?: boolean; href: string; label: string }[]
}

export interface PackagePage {
  slug: string
  content: string
  description?: string
  order?: number
  sidebar_label?: string
  slug: string
  title: string
}

export interface ReferencePage {
  slug: string
  content: string
  description?: string
  order?: number
  sidebar_label?: string
  slug: string
  title: string
}

export interface SeoDefaults {
  canonical_base: string
  meta_description: string
  meta_title: string
  og_image?: string
}

export interface SiteSettings {
  default_locale: string
  og_image?: string
  site_name: string
  site_tagline?: string
  theme_name: string
}

export interface QueryBuilder<T> {
  locale(lang: string): QueryBuilder<T>
  where<K extends keyof T>(field: K, value: T[K]): QueryBuilder<T>
  sort<K extends keyof T>(field: K, order?: 'asc' | 'desc'): QueryBuilder<T>
  limit(n: number): QueryBuilder<T>
  offset(n: number): QueryBuilder<T>
  include(...fields: string[]): QueryBuilder<T>
  first(): T | undefined
  all(): T[]
}

export interface SingletonAccessor<T> {
  locale(lang: string): SingletonAccessor<T>
  include(...fields: string[]): SingletonAccessor<T>
  get(): T
}

export interface DictionaryAccessor {
  locale(lang: string): DictionaryAccessor
  get(): Record<string, string>
  get(key: string): string | undefined
  get(key: string, params: Record<string, string | number>): string
}

export interface DocumentQuery<T> {
  locale(lang: string): DocumentQuery<T>
  where<K extends keyof T>(field: K, value: T[K]): DocumentQuery<T>
  include(...fields: string[]): DocumentQuery<T>
  bySlug(slug: string): T | undefined
  first(): T | undefined
  all(): T[]
}

export declare function query(model: string): QueryBuilder<Record<string, unknown>>

export declare function singleton(model: 'footer'): SingletonAccessor<Footer>
export declare function singleton(model: 'navigation'): SingletonAccessor<Navigation>
export declare function singleton(model: 'seo-defaults'): SingletonAccessor<SeoDefaults>
export declare function singleton(model: 'site-settings'): SingletonAccessor<SiteSettings>
export declare function singleton(model: string): SingletonAccessor<Record<string, unknown>>

export declare function dictionary(model: string): DictionaryAccessor

export declare function document(model: 'docs-page'): DocumentQuery<DocsPage>
export declare function document(model: 'guide-page'): DocumentQuery<GuidePage>
export declare function document(model: 'package-page'): DocumentQuery<PackagePage>
export declare function document(model: 'reference-page'): DocumentQuery<ReferencePage>
export declare function document(model: string): DocumentQuery<Record<string, unknown>>

export interface ContentrainClient {
  query(model: string): QueryBuilder<Record<string, unknown>>
  singleton(model: 'footer'): SingletonAccessor<Footer>
  singleton(model: 'navigation'): SingletonAccessor<Navigation>
  singleton(model: 'seo-defaults'): SingletonAccessor<SeoDefaults>
  singleton(model: 'site-settings'): SingletonAccessor<SiteSettings>
  singleton(model: string): SingletonAccessor<Record<string, unknown>>
  dictionary(model: string): DictionaryAccessor
  document(model: 'docs-page'): DocumentQuery<DocsPage>
  document(model: 'guide-page'): DocumentQuery<GuidePage>
  document(model: 'package-page'): DocumentQuery<PackagePage>
  document(model: 'reference-page'): DocumentQuery<ReferencePage>
  document(model: string): DocumentQuery<Record<string, unknown>>
}

export declare function createContentrainClient(): ContentrainClient

